kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apisvc
  template:
    metadata:
      labels:
        app: apisvc
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: sampleapi
        image: registry-1-stage.docker.io/gdcorbijn/planadevopschallenge1repo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"