kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apisvc
  template:
    metadata:
      labels:
        app: apisvc
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 999
      containers:
      - name: sampleapi
        image: registry-1-stage.docker.io/gdcorbijn/planadevopschallenge1repo:latest
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
            readOnly: true 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock